#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 30 10:01:54 2021

@author: cybree
"""

#from hashlib import sha256
import hashlib

def master_password_gen(): 

    master_password = input("Enter your master password to use for your vault : ").encode()

    compile_factor_together = hashlib.sha256(master_password).hexdigest()
    print("\n[+] Generating your hashed password...\n...\n[+] Your password has been generated")

    return (str(compile_factor_together))

